### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by damianlluch** [Sekhudin/next14-portfolio#1]
Do you have any idea how to create an _app.tsx file in NextJS14 ? I haven't found a document and I need to define a provider for web3-react.js ?

Thanks

**Comment by Sekhudin** [comment]
> Do you have any idea how to create an _app.tsx file in NextJS14 ? I haven't found a document and I need to define a provider for web3-react.js ?
> 
> Thanks

Hello Damian. I don't really understand web3, but if the question is how to create an _app.tsx file in nextjs, you need to pay attention to whether the nextjs you are using is an app router or a pages router? If you are using the NextJS App Router, naming _app.tsx is not supported here. instead you can use layout.tsx in the app folder. For more details, you can visit the official documentation about the routing system here https://nextjs.org/docs/app/building-your-application/routing
